import type { Metadata } from "next";
import { Inter, Inter_Tight, Playfair, Playfair_Display } from "next/font/google";
import "./globals.css";
import Providers from "@/components/providers";
import Footer from "@/components/footer";
import Header from "@/components/header";
import { cn } from "@/lib/utils";

const inter = Inter({
  variable: "--font-sans",
  subsets: ["latin"],
});

const playfair = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-serif",
});

const inter_tight = Inter_Tight({
  variable: "--font-inter-tight",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
    <body
      className={cn(
        'flex min-h-screen flex-col font-sans antialiased',
        inter.variable,
        playfair.variable
      )}
    >
      <Providers>
        <Header />
        <main className='grow'>{children}</main>
        <Footer />
      </Providers>
    </body>
  </html>
  );
}
